---
title: "main"
output: html_document
---
# Librerías
```{r}
source("cod/setup.R")
```

# Pregunta 1
## Función convolución
```{r}
#' Realiza la convolución de dos arreglos/funciones
#' @param arr1 - arreglo num 1 a convolucionar
#' @param arr2 - arreglo num 2 a convolucionar - no importa el orden
convolucion <- function(arr1, arr2){
  # hay que guardar los tamaños de los arreglos porque se modifican in-place
  l1 <- length(arr1)
  l2 <- length(arr2)
  arr1 <- c(arr1, rep(0, l2))
  arr2 <- c(arr2, rep(0, l1)) #                    | 
  # y con un sapply gracias a que R entiende eso   v
  return(sapply(1:(l1+l2-1), function(x) sum(arr1[x:1]*arr2[1:x])))
}
```

## Función bajo el método clásico
```{r}
#' Realiza la compuesta Poisson mediante el método clásico
#' @param lambda - parámetro de la compuesta Poisson
#' @param max - número máximo de x a evaluar
#' @param probs - arreglo de las probabilidades de los reclamos 
c_compuesta <- function(lambda, max, probs){
  n <- max + 1
  mat_conv <- array(0, dim = c(n, n))
  pois <- dpois(0:max, lambda)
  mat_conv[1,1] <- 1
  mat_conv[2:(length(probs)+1),2] <- probs
  ant <- probs
  for(i in 3:n){
    ant <- convolucion(ant, probs)
    t <- min(n, i+length(ant)-1)
    mat_conv[i:t,i] <- ant[1:(t-i+1)]
  }
  return(t(mat_conv %*% pois))
}
```

### Comprobación bajo el ejemplo de la diapositiva
```{r}
c_compuesta(0.8, 6, c(0.25,0.375,0.375))
```

## Ejercicio 4
```{r}
probs <- c(0.1,0.2,0.3,0.4)
c_compuesta(2, 0:4, probs)
```

## Función bajo el método simplificado
```{r}
#' Realiza la compuesta Poisson mediante el método simplificado
#' @param lambda - parámetro de la compuesta Poisson
#' @param montos - arreglo de los reclamos individuales
#' @param probs - arreglo de las probabilidades de los reclamos 
s_compuesta <- function(lambda, montos, probs){
  if(sum(montos%%1!=0) != 0){
    stop("Los montos deben ser enteros")
  }
  n <- sum(montos)
  pois <- probs*lambda
  for(i in 1:length(montos)){
    # hay que tomar los valores enteros para las distribuciones poisson
    valores <- seq(0,n - n%%i, i) 
    res <- rep(0, n+1)
    res[valores+1] <- dpois(0:(length(valores)-1), pois[i])
    if(i == 1){
      conv <- res
    } else {
      conv <- convolucion(conv, res)
    }
  }
  return(conv[1:(n+1)])
}
```

### Comprobación bajo el ejemplo de la diapositiva
```{r}
s_compuesta(0.8, c(1,2,3), c(0.25,0.375,0.375))
```

# Pregunta 2
## Función bajo el método recursivo
```{r}
#' Realiza la compuesta mediante el método recursivo
#' @param densidad - densidad de la compuesta. "Poisson", "Binomial" y "Binomial Negativa"
#' @param params - parámetros de la densidad. Si son dos poner en un arreglo
#' @param max - número máximo de x a evaluar
#' @param probs - arreglo de las probabilidades de los reclamos 
r_compuesta <- function(densidad, params, max, probs){
  fns <- rep(0, max+1)
  if(densidad == "Poisson"){
    if(length(params) !=1){
      stop("La cantidad de parámetros para la Poisson es 1, lambda")
    }
    a <- 0
    b <- params
    fns[1] <- exp(-params)
  } else if(densidad == "Binomial"){
    if(length(params) !=2){
      stop("La cantidad de parámetros para la Binomial son 2, n y q")
    }
    if(params[1]%%1 != 0){
      stop("El parámetro n debe de ser entero")
    }
    a <- -params[2]/(1-params[2])
    b <- (params[1]+1)*params[2]/(1-params[2])
    fns[1] <- (1-params[2])^params[1]
  } else if(densidad == "Binomial Negativa"){
    if(length(params) !=2){
      stop("La cantidad de parámetros para la Binomial Negativa son 2, r y beta")
    }
    a <- params[2]/(1+params[2])
    b <- (params[1]-1)*params[2]/(1+params[2])
    fns[1] <- (1+params[2])^(-params[1])
  } else {
    stop("La densidad indicada no es ni la Poisson, Binomial ni Binomial Negativa")
  }
  
  # Inicia el proceso recursivo
  for(i in 1:max){
    conv <- rep(0, i)
    conv[1:min(i,length(probs))] <- probs[1:min(i,length(probs))] 
    conv <- conv * fns[i:1]
    fns[i+1] <-  sum(conv[1:i] * (a + b*(1:i)/i))
  }
  
  return(fns)
}
```

### Comprobación bajo el ejemplo de la diapositiva
```{r}
r_compuesta("Poisson", 0.8, 6, c(0.25,0.375,0.375))
```

## Ejercicio 11
```{r}
probs <- c(0.7, 0.3)
res <- data.frame(
  t(data.frame(Poisson = r_compuesta("Poisson", 4.5, 5, probs),
               Binomial_Negativa = r_compuesta("Binomial Negativa", c(4.5, 0.5), 5, probs),
               Binomial = r_compuesta("Binomial", c(9, 0.5), 5, probs))))
names(res) <-  0:5
res
```































